***************
*** 5,10 ****
  RUN apt-get -y install locales && \
      localedef -f UTF-8 -i ja_JP ja_JP.UTF-8
  RUN apt-get install -y vim less
  
  ENV LANG ja_JP.UTF-8
  ENV LANGUAGE ja_JP:ja
--- 5,11 ----
  RUN apt-get -y install locales && \
      localedef -f UTF-8 -i ja_JP ja_JP.UTF-8
  RUN apt-get install -y vim less
+ RUN apt-get install -y default-jdk
  
  ENV LANG ja_JP.UTF-8
  ENV LANGUAGE ja_JP:ja
