version: '2.12'
services:
    react_app:
        build: ./dockerfiles/react
        container_name: react_app
        restart: always
        volumes:
            - ./dockerfiles/react/src/:/usr/src/app
        command: sh -c "cd react-app &&yarn install && yarn run start"
        expose:
            - "3000"
    nginx:
        image: nginx:latest
        container_name: nginx
        restart: always
        ports:
          - 10180:80
        volumes:
          - ./dockerfiles/react/src/react-app/build:/var/www
          - ./dockerfiles/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
          - react_app
