version: '2.12'
services:
    api:
        build: ./dockerfiles/api
        container_name: 'api'
        #restart: always
        tty: true
        volumes:
            - ./dockerfiles/api/src/:/root/src
#        command: sh -c "flask --debug run -h 0.0.0.0 -p 9000"
#        ports:
#          - 9000:9000

        command: sh -c "flask --debug run -h api -p 9000"
        expose:
#            - "2900"
            - "9000"

    react_app:
        build: ./dockerfiles/react
        container_name: react_app
        #restart: always
        volumes:
            - ./dockerfiles/react/src/:/usr/src/app
        command: sh -c "cd react-app &&yarn install && yarn run start"
        ports:
          - 10280:10280
            
#        expose:
#            - "3000"
    nginx:
        image: nginx:latest
        container_name: nginx
        #restart: always
        ports:
          - 10180:80
        volumes:
#          - ./dockerfiles/react/src/react-app/build:/var/www
          - ./dockerfiles/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
          - react_app
          - api

    
