version: '2.12'
services:
    db:
        build: ./db
        image: mysql
        container_name: "SQL_LOGIN"
        environment:
            MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASS}
            TZ: ${TZ}
        expose:
            - "3306"
        volumes:
          - ./db/initdb.d:/docker-entrypoint-initdb.d
          - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
          - ./db/mysql:/var/lib/mysql
    
    express:
        build: ./express #Dockerfileの親フォルダ
        container_name: "express-sql_login"
        tty: true
        environment:
            - NODE_ENV=DEVELOPMENT
            # - PORT=${DB_PORT}
            - EXPRESS_PORT=${EXPRESS_PORT}
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASS=${DB_PASS}
            - DB_HOST=${DB_HOST}  
            - JWT_SECRET=${JWT_SECRET}
            - JWT_EXPIRES=${JWT_EXPIRES}
            - COOKIE_EXPIRES=${COOKIE_EXPIRES}
        volumes:
            - ./express/:/usr/src/app/
        ports:
            - 8080:8080
        working_dir: /usr/src/app/src
        command: sh -c "npm install && npm install -g nodemon && nodemon"
        depends_on:
            - db
        links:
            - db:db

